package com.example.data

import android.content.Context
import android.util.Log
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.GetCredentialResponse
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.Firebase
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.auth.auth
import kotlinx.coroutines.tasks.await
import java.security.MessageDigest
import java.util.UUID

object AuthManager {
    private const val TAG = "AuthManager"
    // To properly use this, the user needs to configure their Web Client ID in the strings.xml or via Secrets.
    // For now we will try to read it from strings, if not present it will fail gracefully.
    
    val isFirebaseAvailable: Boolean
        get() = try { Firebase.auth; true } catch (e: Exception) { false }

    suspend fun signInWithGoogle(context: Context): Boolean {
        if (!isFirebaseAvailable) {
            Log.e(TAG, "Firebase not available")
            return false
        }
        val credentialManager = CredentialManager.create(context)
        
        // This requires a Web Client ID. We use a placeholder if not set, which will cause a natural failure.
        // In a real scenario, you retrieve this from R.string.default_web_client_id generated by google-services
        val webClientId = try {
            val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
            if (resId != 0) context.getString(resId) else "PLACEHOLDER_CLIENT_ID"
        } catch (e: Exception) {
            "PLACEHOLDER_CLIENT_ID"
        }

        val rawNonce = UUID.randomUUID().toString()
        val bytes = rawNonce.toByteArray()
        val md = MessageDigest.getInstance("SHA-256")
        val digest = md.digest(bytes)
        val hashedNonce = digest.fold("") { str, it -> str + "%02x".format(it) }

        val googleIdOption = GetGoogleIdOption.Builder()
            .setFilterByAuthorizedAccounts(false)
            .setServerClientId(webClientId)
            .setNonce(hashedNonce)
            .build()

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(googleIdOption)
            .build()

        return try {
            val result = credentialManager.getCredential(
                request = request,
                context = context
            )
            handleSignInResult(result)
        } catch (e: Exception) {
            Log.e(TAG, "Google Sign In Failed", e)
            false
        }
    }

    private suspend fun handleSignInResult(result: GetCredentialResponse): Boolean {
        val credential = result.credential
        if (credential is CustomCredential && credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
            try {
                val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
                val idToken = googleIdTokenCredential.idToken
                
                val authCredential = GoogleAuthProvider.getCredential(idToken, null)
                Firebase.auth.signInWithCredential(authCredential).await()
                return true
            } catch (e: Exception) {
                Log.e(TAG, "Firebase Auth Failed", e)
                return false
            }
        }
        return false
    }
    
    fun signOut() {
        if (isFirebaseAvailable) {
            Firebase.auth.signOut()
        }
    }
}
