name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        validate-wrappers: false
        gradle-version: '8.9'
        
    - name: Create dummy google-services.json
      run: |
        echo '{"project_info": {"project_number": "123","firebase_url": "https://test.firebaseio.com","project_id": "test","storage_bucket": "test.appspot.com"},"client": [{"client_info": {"mobilesdk_app_id": "1:123:android:123","android_client_info": {"package_name": "com.aistudio.xeditor.abcfgh"}},"oauth_client": [],"api_key": [{"current_key": "dummy"}],"services": {"appinvite_service": {"other_platform_oauth_client": []}}}]}' > app/google-services.json
      
    - name: Build with Gradle
      run: gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
